name: Deploy

on:
  push: 
     branches:
      - 'dev'
jobs:

  checkout:
    uses : ADE-CASE/case-workflows/.github/workflows/checkout.yml@main
    
  docker:
    uses : ADE-CASE/case-workflows/.github/workflows/docker.yml@main
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
