name: Deploy

on:
  push: 
     branches:
      - 'main'
      - 'staging'
      - 'dev'

jobs:

  checkout:
    uses : ADE-CASE/case-workflows/.github/workflows/checkout.yml@main
    
  production:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses : ADE-CASE/case-workflows/.github/workflows/docker.yml@main
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
  
  staging:
    if: ${{ github.ref == 'refs/heads/staging' }}
    uses : ADE-CASE/case-workflows/.github/workflows/docker.yml@main
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
  
  development:
    if: ${{ github.ref == 'refs/heads/dev' }}
    uses : ADE-CASE/case-workflows/.github/workflows/docker.yml@main
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
