name: Deploy

on:
  push: 
     branches:
      - 'main'
      - 'staging'
      - 'dev'
    #  tags:
    #   - v*-dev
    #   - v*-prod
    #   - v*-staging

jobs:

  checkout:
    uses : ADE-CASE/case-workflows/.github/workflows/checkout.yml@main
    
  production:
    # if: (github.event.base_ref == 'refs/heads/production') && (endsWith(github.event.ref, 'prod'))
    if: ${{ github.ref == 'refs/heads/main' }}
    uses : ADE-CASE/case-workflows/.github/workflows/docker.yml@main
    secrets:
      dh_username: ${{ secrets.DH_USERNAME }}
      dh_token: ${{ secrets.DH_TOKEN }}
      manggile: ${{ secrets.MANGGIL }}
  
  staging:
    # if: (github.event.base_ref == 'refs/heads/staging') && (endsWith(github.event.ref, 'staging'))
    if: ${{ github.ref == 'refs/heads/staging' }}
    uses : ADE-CASE/case-workflows/.github/workflows/docker.yml@main
    secrets:
      dh_username: ${{ secrets.DH_USERNAME }}
      dh_token: ${{ secrets.DH_TOKEN }}
      manggile: ${{ secrets.MANGGIL }}
  
  development:
    # if: (github.event.base_ref != 'refs/heads/production') && (endsWith(github.event.ref, 'dev'))
    if: ${{ github.ref == 'refs/heads/dev' }}
    uses : ADE-CASE/case-workflows/.github/workflows/docker.yml@main
    secrets:
      dh_username: ${{ secrets.DH_USERNAME }}
      dh_token: ${{ secrets.DH_TOKEN }}
      manggile: ${{ secrets.MANGGIL }}
